apiVersion: v1
items:
- apiVersion: ptp.openshift.io/v1
  kind: PtpOperatorConfig
  metadata:
    generation: 2
    name: default
    namespace: openshift-ptp
  spec:
    daemonNodeSelector:
      node-role.kubernetes.io/worker: ""
    ptpEventConfig:
      enableEventPublisher: true
      transportHost: amqp://amq-interconnect.amq-interconnect.svc.cluster.local
kind: List
metadata:
  resourceVersion: ""

